/*
 * This file is generated by jOOQ.
 */
package com.example.myproject.jooq;


import com.example.myproject.jooq.tables.Employee;
import com.example.myproject.jooq.tables.FlywaySchemaHistory;
import com.example.myproject.jooq.tables.Person;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = 1455467037;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.employee</code>.
     */
    public final Employee EMPLOYEE = com.example.myproject.jooq.tables.Employee.EMPLOYEE;

    /**
     * The table <code>jooq.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.myproject.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooq.person</code>.
     */
    public final Person PERSON = com.example.myproject.jooq.tables.Person.PERSON;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Employee.EMPLOYEE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Person.PERSON);
    }
}
