/*
 * This file is generated by jOOQ.
 */
package com.example.myproject.jooq;


import com.example.myproject.jooq.tables.Employee;
import com.example.myproject.jooq.tables.FlywaySchemaHistory;
import com.example.myproject.jooq.tables.Person;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.employee</code>.
     */
    public static final Employee EMPLOYEE = com.example.myproject.jooq.tables.Employee.EMPLOYEE;

    /**
     * The table <code>jooq.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.myproject.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooq.person</code>.
     */
    public static final Person PERSON = com.example.myproject.jooq.tables.Person.PERSON;
}
