/*
 * This file is generated by jOOQ.
 */
package com.example.myproject.jooq.tables.records;


import com.example.myproject.jooq.tables.Employee;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record10<Integer, String, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 513275970;

    /**
     * Setter for <code>jooq.employee.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.employee.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq.employee.emp_um</code>.
     */
    public void setEmpUm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.employee.emp_um</code>.
     */
    public String getEmpUm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq.employee.emp_name</code>.
     */
    public void setEmpName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq.employee.emp_name</code>.
     */
    public String getEmpName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq.employee.age</code>.
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq.employee.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jooq.employee.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jooq.employee.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jooq.employee.tele_num</code>.
     */
    public void setTeleNum(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jooq.employee.tele_num</code>.
     */
    public String getTeleNum() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jooq.employee.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jooq.employee.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jooq.employee.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>jooq.employee.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>jooq.employee.update_by</code>.
     */
    public void setUpdateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jooq.employee.update_by</code>.
     */
    public String getUpdateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jooq.employee.update_date</code>.
     */
    public void setUpdateDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>jooq.employee.update_date</code>.
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Employee.EMPLOYEE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employee.EMPLOYEE.EMP_UM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Employee.EMPLOYEE.EMP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Employee.EMPLOYEE.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Employee.EMPLOYEE.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Employee.EMPLOYEE.TELE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Employee.EMPLOYEE.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Employee.EMPLOYEE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Employee.EMPLOYEE.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return Employee.EMPLOYEE.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmpUm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTeleNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmpUm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTeleNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value2(String value) {
        setEmpUm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value3(String value) {
        setEmpName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value4(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value6(String value) {
        setTeleNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value7(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value8(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value9(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value10(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Integer id, String empUm, String empName, Integer age, String address, String teleNum, String createBy, LocalDateTime createDate, String updateBy, LocalDateTime updateDate) {
        super(Employee.EMPLOYEE);

        set(0, id);
        set(1, empUm);
        set(2, empName);
        set(3, age);
        set(4, address);
        set(5, teleNum);
        set(6, createBy);
        set(7, createDate);
        set(8, updateBy);
        set(9, updateDate);
    }
}
